services:
    phpbbmodders.editedpostsunread.listener:
        class: phpbbmodders\editedpostsunread\event\listener
        arguments:
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
